
services:
  db:
    image: postgres:15
    container_name: blogdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ../Blog-backend
      dockerfile: Blog.Api/Dockerfile
    container_name: blogapi
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=blogdb;Username=postgres;Password=postgres"
    depends_on:
      - db
    ports:
      - "5000:8080"
      - "5001:8081"

  front:
    build:
      context: ../Blog-frontend/blog-frontend
      dockerfile: Dockerfile
    container_name: blogfront
    ports:
      - "3000:80"
    depends_on:
      - api


volumes:
  pgdata: